name: Sync Code to AtomGit

on:
  push:
    branches: [main, v0]

jobs:
  sync-code-to-atomgit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: adambirds/sync-github-to-gitlab-action@v1.1.0
        with:
          destination_repository: git@atomgit.com:naiba/nezha-scripts.git
          destination_branch_name: ${{ github.ref_name }}
          destination_ssh_key: ${{ secrets.ATOMGIT_SSH_KEY }}
